blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/ScratchAddons/ScratchAddons/discussions/new?category_id=16783727
    about: Needs discussion (moved to Discussions)
  - name: ❓ Help/questions
    url: https://github.com/ScratchAddons/ScratchAddons/discussions/new?category_id=16783729
    about: Ask a question (moved to Discussions)
  - name: 📝 Send feedback
    url: https://scratchaddons.com/feedback
    about: Send a general feedback on our website
  - name: 💬 GitHub Discussions
    url: https://github.com/ScratchAddons/ScratchAddons/discussions
    about: Discuss about Scratch Addons on our GitHub Discussions (our own forums)
